### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by MNDLZZ** [mbahArip/japanLicensePlate_Generator#3]
**Describe your Request**
If possible get specific kanagawa plate to the Japan License Plate Generator it's meant for a specific project car that will make it to a 3d model car for games purpose; i tryed searching images of this license plate but only found one as reference sadly.

**Screenshot**
![fujisawa plate kanagawa](https://github.com/user-attachments/assets/34878b33-67ef-4ab7-b4c5-5fa39f9174f8)

**Additional context**
additionally i would say  that this is just an if possible request, since i couldn't found any better info or images about this specific plate.

**Comment by mbahArip** [comment]
The screenshot you provided is Tama plate
You can find it on Kanto > Tokyo > Kunitachi > Tama
![image](https://github.com/user-attachments/assets/3c197249-5ac0-4c1f-8ec7-4da5053b483e)

**Comment by MNDLZZ** [comment]
oh, thank you so much for the help since i was lost with google misinformation related to the plate.
